version: '3.8'

services:
  bot:
    build: .
    container_name: internship_bot
    restart: unless-stopped
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - TZ=UTC
